//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExam.Models{    using System;    using System.Collections.Generic;    public partial class QuestionCategoryJson    {        public int RandomKey { get; set; }        public int Sequence { get; set; }        public string Title { get; set; }        public int Quantity { get; set; }        public double ScorePerQuestion { get; set; }        public string QuestionType { get; set; }        public List<ChoiceJson> ChoiceList { get; set; }        public List<EssayJson> EssayList { get; set; }        public QuestionCategoryJson()
        {
            ChoiceList = new List<ChoiceJson>();
            EssayList = new List<EssayJson>();
            QuestionType = global::OnlineExam.QuestionType.ShortAnswer.ToString();
            Title = OnlineExam.QuestionType.ShortAnswer.GetInfo();
            ScorePerQuestion = 4;
            Sequence = 1;


        }    }    public partial class ChoiceJson    {
        public ChoiceJson()        {            ID = -1;            Description = "";            Frequency = 0;            Difficulty = 0;
            OptionD = OptionE = OptionF = "";            Info = "";            Score = 2;            SmallQuestionNumber = BigQuestionNumber = 1;        }
        public long ID { get; set; }
        public string Question { get; set; }
        public int SmallQuestionNumber { get; set; }
        public int BigQuestionNumber { get; set; }
        public double Score { get; set; }        public string OptionA { get; set; }
        public string OptionB { get; set; }
        public string OptionC { get; set; }
        public string OptionD { get; set; }
        public string OptionE { get; set; }
        public string OptionF { get; set; }        public bool AisTrue { get; set; }        public bool BisTrue { get; set; }        public bool CisTrue { get; set; }        public bool DisTrue { get; set; }        public bool EisTrue { get; set; }        public bool FisTrue { get; set; }        public bool IsMultiple { get; set; }
        public string QuestionType { get; set; }
        public string Info { get; set; }
        public short Difficulty { get; set; }
        public short Frequency { get; set; }
        public string Description { get; set; }
    }    public partial class EssayJson    {
        public EssayJson()        {            ID = -1;            Description = "";            Frequency = 0;            Difficulty = 0;
        }
        public long ID { get; set; }
        public string Question { get; set; }
        public int SmallQuestionNumber { get; set; }
        public int BigQuestionNumber { get; set; }
        public double Score { get; set; }        public string QuestionType { get; set; }
        public string Answer { get; set; }
        public string Info { get; set; }
        public short Difficulty { get; set; }
        public short Frequency { get; set; }
        public string Description { get; set; }    }}