//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExam.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExamEntities : DbContext
    {
        public ExamEntities()
            : base("name=ExamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Grade> Grade { get; set; }
        public virtual DbSet<Major> Major { get; set; }
        public virtual DbSet<Major_Subject> Major_Subject { get; set; }
        public virtual DbSet<Paper_AnswerList> Paper_AnswerList { get; set; }
        public virtual DbSet<Paper_Choice> Paper_Choice { get; set; }
        public virtual DbSet<Paper_Essay> Paper_Essay { get; set; }
        public virtual DbSet<Paper_QuestionCategory> Paper_QuestionCategory { get; set; }
        public virtual DbSet<PaperCollection> PaperCollection { get; set; }
        public virtual DbSet<Permission> Permission { get; set; }
        public virtual DbSet<QuestionChoice> QuestionChoice { get; set; }
        public virtual DbSet<QuestionCollection> QuestionCollection { get; set; }
        public virtual DbSet<QuestionEssay> QuestionEssay { get; set; }
        public virtual DbSet<Resource> Resource { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
        public virtual DbSet<Subject_Choice> Subject_Choice { get; set; }
        public virtual DbSet<Subject_Essay> Subject_Essay { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teacher_Subject> Teacher_Subject { get; set; }
        public virtual DbSet<TestPaper> TestPaper { get; set; }
        public virtual DbSet<User_Subject> User_Subject { get; set; }
        public virtual DbSet<UserProfile> UserProfile { get; set; }
        public virtual DbSet<Paper_AnswerList_Item> Paper_AnswerList_Item { get; set; }
    }
}
