//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paper_QuestionCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paper_QuestionCategory()
        {
            this.Paper_Choice = new HashSet<Paper_Choice>();
            this.Paper_Essay = new HashSet<Paper_Essay>();
        }
    
        public string PaperID { get; set; }
        public int Sequence { get; set; }
        public string Title { get; set; }
        public int Quantity { get; set; }
        public double ScorePerQuestion { get; set; }
        public string QuestionType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paper_Choice> Paper_Choice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paper_Essay> Paper_Essay { get; set; }
        public virtual TestPaper TestPaper { get; set; }
    }
}
