//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paper_AnswerList_Item
    {
        public long AnswerListID { get; set; }
        public int BigQuestionNumber { get; set; }
        public int SmallQuestionNumber { get; set; }
        public string Answer { get; set; }
        public Nullable<double> Score { get; set; }
        public Nullable<bool> IsCorrect { get; set; }
    
        public virtual Paper_AnswerList Paper_AnswerList { get; set; }
    }
}
